name: Fizz Buzz Python
services:
  main:
    type: python
    build:
      - chmod +x bin/fizzbuzz
tooling:
  fizzbuzz:
    service: main
    cmd: ./bin/fizzbuzz
  lint:
    service: main
    cmd: pylint *.py
  test:
    service: main
    cmd: nosetests --rednose