name: validation
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Prepare
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run:  pylint *.py
      - name: Test
        run: nosetests
